[package]
name = "nvapi"
version = "0.0.3"
authors = ["arcnmx"]

description = "NVIDIA NVAPI bindings"
keywords = ["nvidia", "nvapi", "gtx"]

documentation = "http://arcnmx.github.io/nvapi-rs/nvapi"
repository = "https://github.com/arcnmx/nvapi-rs"
readme = "README.md"
license = "MIT"

[dependencies]
nvapi-sys = { version = "0.0.3", path = "sys", default-features = false }
serde = { version = "^1.0.0", optional = true }
serde_derive = { version = "^1.0.0", optional = true }
i2c = { version = "^0.0.1", optional = true, git = "https://github.com/arcnmx/i2c-rs.git" }
void = "1.0.2"
log = "0.3.8"

[features]
serde_types = ["serde", "serde_derive", "nvapi-sys/serde_types"]
default = ["serde_types"]
