[package]
name = "nvapi-sys"
version = "0.0.4"
authors = ["arcnmx"]

description = "NVIDIA NVAPI FFI bindings"
keywords = ["nvidia", "nvapi", "gtx"]

documentation = "http://arcnmx.github.io/nvapi-rs/nvapi_sys"
repository = "https://github.com/arcnmx/nvapi-rs"
readme = "../README.md"
license = "MIT"

[target.'cfg(windows)'.dependencies]
#winapi = { version = "0.3", features = ["libloaderapi", "unknwnbase"] }
winapi = "0.2"
kernel32-sys = "0.2"

[dependencies]
bitflags = "1.0.0"
serde = { version = "^1.0.0", optional = true }
serde_derive = { version = "^1.0.0", optional = true }

[features]
serde_types = ["serde", "serde_derive"]
default = ["serde_types"]
